### ISSUE TITLE
Test improvements + new case

### ISSUE THREAD

**Issue by szarouski** [jfromaniello/npm-install-retry#7]
Hi, I fixed tests for windows and added [Travis](https://travis-ci.org/szarouski/npm-install-retry) and [Appveyor](https://ci.appveyor.com/project/szarouski/npm-install-retry) (windows) CI support. I also added new check for `npm ERR! errno ECONNRESET` as it is similar to `npm ERR! cb() never called` in a sense that it is happening sporadically... Changes are in my branch and you can see what changed [here](https://github.com/jfromaniello/npm-install-retry/compare/master...szarouski:feature/support-for-connection-reset-errors). If I can be added to a list of collaborators for this repo I would love to merge my changes and bring CI icons to readme :smile: . What do you think?

**Comment by SwinX** [comment]
👍 for this issue. It would be really nice to evolve this instrument so it may be used broadly.
By the way, during your research have you tried to to somehow integrate to npm itself in order to not retry overall install but to retry only failed module ?

**Comment by szarouski** [comment]
@SwinX I didn't, I was pretty much following what @jfromaniello was doing. It is reading stdout and stderr and if there is a match to a pattern, once the process finish running (either with error or success), it will restart `npm install`. I think good part is that if some packages actually installed before failure, npm will not install them again, so time is not wasted. I agree with you that if we can customize a script to read patterns from some config (package.json or env variables?), then the tool will become more flexible. That will be the next step.

Also it took me a while but I found better solution for the issue with ECONNRESET - reason why I started to customize this package. There was a bug in node core what was fixed starting from version 4.4 (also some versions of 5 have that issue as well). More information can be found here: https://github.com/npm/registry/issues/10.

**Comment by jfromaniello** [comment]
Good work, can you send me a PR? :)

**Comment by szarouski** [comment]
PR created: https://github.com/jfromaniello/npm-install-retry/pull/8. You might want to create your own account on https://travis-ci.org and https://ci.appveyor.com (it is very easy + you can login via github) to keep badges up to date as the reference my repo at the moment.
